### ISSUE TITLE
Diferencias Alternativas de las preguntas con las respuestas.

### ISSUE THREAD

**Issue by EnriqueR20** [AlexanderHuisa/trivia_silabuz#1]
La trivia es muy buena solo deberías cambiar los colores de las alternativas para que se diferencie de la respuesta correcta.

![isssus](https://user-images.githubusercontent.com/113269346/190284610-88591886-e17f-4f01-8bc2-5573f0e5e10f.png)

**Comment by AlexanderHuisa** [comment]
Si, tienes razón. Ya están los cambios, así quedaron.

![image](https://user-images.githubusercontent.com/68964232/190290091-e66bbc19-ac8d-4f88-acb9-88b3dd94c376.png)
