### ISSUE TITLE
Resaltar Respuesta Correcta

### ISSUE THREAD

**Issue by EnriqueR20** [AlexanderHuisa/trivia_silabuz#2]
Tu Trivia es muy buena solo un aspecto a mejorar seria resaltar con un color la repuesta que debería ser la correcta.
![tosajo](https://user-images.githubusercontent.com/113269346/190837107-a3cf0dd9-aa75-4ae2-b3fe-b9d009a6a2ad.png)

**Comment by AlexanderHuisa** [comment]
Gracias por su observación, ya realice los cambios respectivos.
![image](https://user-images.githubusercontent.com/68964232/190839883-a3109425-d22c-4a28-9cc8-571f8cbdf3a2.png)
